services:
  - type: web
    name: beer-bot        # Можете изменить имя сервиса, если хотите
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt" # Обновим команду сборки
    startCommand: "python bot.py"
    pythonVersion: 3.11.9 # Используем стабильную версию Python
    envVars:
      - key: BOT_TOKEN
        sync: false       # Это указывает, что значение будет браться из вашего дашборда Render
